"""
slot_registry.py — Authoritative public contract for all 47 typed slots.
Single source of truth. Generated documentation must consume this; it must
not become a second independent source.

HOKOM-TAAQOL-SGA-POST-CLOSURE-HARDENING-01
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import FrozenSet, Optional

from pipeline.sga.contracts import SlotId, SlotSort, SlotState


@dataclass(frozen=True)
class SlotContract:
    slot_id: SlotId
    serialized_id: str          # stable string key (must equal slot_id.value)
    sort: SlotSort
    stage: str                  # H0, H1, ... H15, EVIDENCE, RESIDUAL
    semantic_purpose: str
    value_type: str             # e.g. "str", "tuple[str,...]", "PhonologicalSlot"
    cardinality: str            # SINGLE | MULTI
    nullable: bool
    absence_legal: bool         # UNKNOWN or NOT_APPLICABLE ok
    multi_valued_legal: bool
    ambiguity_legal: bool
    provenance_required: bool
    evidence_required: bool
    valid_producers: FrozenSet[str]
    valid_consumers: FrozenSet[str]
    participates_in_claim_key: bool
    participates_in_eval_identity: bool
    stability: str              # STABLE | PROVISIONAL | RESERVED | DEPRECATED
    classification: str         # REQUIRED | OPTIONAL | CONDITIONAL | MULTI_VALUED | AMBIGUOUS_CAPABLE | PROVENANCE_REQUIRED | RESERVED
    compatibility_notes: str = ""


# Registry — one entry per SlotId
SLOT_REGISTRY: dict[SlotId, SlotContract] = {

    # ── H0: Surface Identity ───────────────────────────────────────────────────

    SlotId.ORIGINAL_SURFACE: SlotContract(
        slot_id=SlotId.ORIGINAL_SURFACE,
        serialized_id="ORIGINAL_SURFACE",
        sort=SlotSort.SURFACE_IDENTITY,
        stage="H0",
        semantic_purpose="The unmodified Arabic surface form as received by the pipeline; provenance anchor for all downstream slots",
        value_type="str",
        cardinality="SINGLE",
        nullable=False,
        absence_legal=False,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=True,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="REQUIRED",
    ),

    SlotId.NORMALIZED_SURFACE: SlotContract(
        slot_id=SlotId.NORMALIZED_SURFACE,
        serialized_id="NORMALIZED_SURFACE",
        sort=SlotSort.NORMALIZATION,
        stage="H1",
        semantic_purpose="NFC-normalized surface; may differ from original by canonical decomposition only; base for phonological analysis",
        value_type="str",
        cardinality="SINGLE",
        nullable=False,
        absence_legal=False,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=True,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="REQUIRED",
    ),

    # ── H2: Phonological ──────────────────────────────────────────────────────

    SlotId.LETTER_SEQUENCE: SlotContract(
        slot_id=SlotId.LETTER_SEQUENCE,
        serialized_id="LETTER_SEQUENCE",
        sort=SlotSort.PHONOLOGICAL,
        stage="H2",
        semantic_purpose="Ordered sequence of base Arabic letters extracted from the normalized surface",
        value_type="tuple[str,...]",
        cardinality="MULTI",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
        compatibility_notes="Not yet populated by the live pipeline; UNKNOWN is expected",
    ),

    SlotId.DIACRITIC_SEQUENCE: SlotContract(
        slot_id=SlotId.DIACRITIC_SEQUENCE,
        serialized_id="DIACRITIC_SEQUENCE",
        sort=SlotSort.PHONOLOGICAL,
        stage="H2",
        semantic_purpose="Ordered sequence of Arabic diacritics (tashkeel) aligned with LETTER_SEQUENCE",
        value_type="tuple[str,...]",
        cardinality="MULTI",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
        compatibility_notes="Not yet populated by the live pipeline; UNKNOWN is expected",
    ),

    SlotId.PHONOLOGICAL_CELLS: SlotContract(
        slot_id=SlotId.PHONOLOGICAL_CELLS,
        serialized_id="PHONOLOGICAL_CELLS",
        sort=SlotSort.PHONOLOGICAL,
        stage="H2",
        semantic_purpose="Phonological cell decomposition (CV structure) as defined by slot_engineering.py SLOT_TRANS automaton",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline", "slot_engineering"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
        compatibility_notes="Populated by slot_engineering.py phonological automaton; absence legal in most paths",
    ),

    SlotId.SHADDA_SLOT: SlotContract(
        slot_id=SlotId.SHADDA_SLOT,
        serialized_id="SHADDA_SLOT",
        sort=SlotSort.PHONOLOGICAL,
        stage="H2",
        semantic_purpose="Position and nature of shaddah (gemination marker) in the surface form",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="Only present when surface has shaddah; NOT_APPLICABLE otherwise",
    ),

    SlotId.SUKUN_SLOT: SlotContract(
        slot_id=SlotId.SUKUN_SLOT,
        serialized_id="SUKUN_SLOT",
        sort=SlotSort.PHONOLOGICAL,
        stage="H2",
        semantic_purpose="Position and nature of sukun (vowellessness marker) in the surface form",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="Only present when surface has sukun; NOT_APPLICABLE otherwise",
    ),

    SlotId.MADD_SLOT: SlotContract(
        slot_id=SlotId.MADD_SLOT,
        serialized_id="MADD_SLOT",
        sort=SlotSort.PHONOLOGICAL,
        stage="H2",
        semantic_purpose="Position and nature of madd (vowel elongation) in the surface form",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="Only present when surface has madd; NOT_APPLICABLE otherwise",
    ),

    # ── H3: Segmentation ──────────────────────────────────────────────────────

    SlotId.PROCLITIC_SLOTS: SlotContract(
        slot_id=SlotId.PROCLITIC_SLOTS,
        serialized_id="PROCLITIC_SLOTS",
        sort=SlotSort.SEGMENTATION,
        stage="H3",
        semantic_purpose="Ordered tuple of proclitic particles attached before the segment host (waw, fa, ba, la, ka, sa...)",
        value_type="tuple[str,...]",
        cardinality="MULTI",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="MULTI_VALUED",
        compatibility_notes="NOT_APPLICABLE when no proclitics present",
    ),

    SlotId.SEGMENT_HOST: SlotContract(
        slot_id=SlotId.SEGMENT_HOST,
        serialized_id="SEGMENT_HOST",
        sort=SlotSort.SEGMENTATION,
        stage="H3",
        semantic_purpose="The lexical host token after clitic segmentation; the morphological center for SlotGraph; never original_surface when clitics are present",
        value_type="str",
        cardinality="SINGLE",
        nullable=False,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="UNKNOWN only for pure-clitic constructions with no lexical host",
    ),

    SlotId.ENCLITIC_SLOTS: SlotContract(
        slot_id=SlotId.ENCLITIC_SLOTS,
        serialized_id="ENCLITIC_SLOTS",
        sort=SlotSort.SEGMENTATION,
        stage="H3",
        semantic_purpose="Ordered tuple of enclitic particles attached after the segment host (pronominal suffixes, accusative nun, etc.)",
        value_type="tuple[str,...]",
        cardinality="MULTI",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="MULTI_VALUED",
        compatibility_notes="NOT_APPLICABLE when no enclitics present",
    ),

    # ── H4: Article ───────────────────────────────────────────────────────────

    SlotId.ARTICLE_SLOT: SlotContract(
        slot_id=SlotId.ARTICLE_SLOT,
        serialized_id="ARTICLE_SLOT",
        sort=SlotSort.ARTICLE,
        stage="H4",
        semantic_purpose="Presence and form of the Arabic definite article (AL) attached to the segment host",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE when no article present; value='AL' when present",
    ),

    SlotId.SOLAR_ASSIMILATION_SLOT: SlotContract(
        slot_id=SlotId.SOLAR_ASSIMILATION_SLOT,
        serialized_id="SOLAR_ASSIMILATION_SLOT",
        sort=SlotSort.ARTICLE,
        stage="H4",
        semantic_purpose="Solar assimilation of the lam in the definite article (AL→assimilated to initial letter for solar letters)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE when article absent or letter is lunar; value='SOLAR' for solar letters",
    ),

    # ── H5: Boundary ──────────────────────────────────────────────────────────

    SlotId.BOUNDARY_TYPE_SLOT: SlotContract(
        slot_id=SlotId.BOUNDARY_TYPE_SLOT,
        serialized_id="BOUNDARY_TYPE_SLOT",
        sort=SlotSort.BOUNDARY,
        stage="H5",
        semantic_purpose="Type of morphological boundary: OPERATOR_BOUNDARY (harf), MABNI_BOUNDARY (indeclinable ism), JAMID_AALAM_BOUNDARY (proper noun jamid), or absent (open morphology)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE when word has open morphology",
    ),

    SlotId.PATH_DIRECTIVE_SLOT: SlotContract(
        slot_id=SlotId.PATH_DIRECTIVE_SLOT,
        serialized_id="PATH_DIRECTIVE_SLOT",
        sort=SlotSort.BOUNDARY,
        stage="H5",
        semantic_purpose="Processing path directive derived from boundary type: OPEN_MORPHOLOGY (proceed to root analysis) or ROOT_PATH_BLOCKED (closed boundary, skip root layer)",
        value_type="str",
        cardinality="SINGLE",
        nullable=False,
        absence_legal=False,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline", "adapters"}),
        valid_consumers=frozenset({"bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="REQUIRED",
        compatibility_notes="Always FILLED; BLOCKED state when boundary prevents root analysis",
    ),

    # ── H5-H6: Lexical / Functional Identity ──────────────────────────────────

    SlotId.LEXICAL_IDENTITY_SLOT: SlotContract(
        slot_id=SlotId.LEXICAL_IDENTITY_SLOT,
        serialized_id="LEXICAL_IDENTITY_SLOT",
        sort=SlotSort.LEXICAL_FUNCTIONAL,
        stage="H5",
        semantic_purpose="Canonical lexical identity label for the token (e.g., functional catalog entry ID for particles and pronouns)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
    ),

    SlotId.FUNCTIONAL_OWNER_SLOT: SlotContract(
        slot_id=SlotId.FUNCTIONAL_OWNER_SLOT,
        serialized_id="FUNCTIONAL_OWNER_SLOT",
        sort=SlotSort.LEXICAL_FUNCTIONAL,
        stage="H5",
        semantic_purpose="Functional ownership label for the token — identifies the operator or mabni class that governs this token (e.g., ISM_SHART, DAMIR, QUESTION_WORD)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for ROOT_CLAIM profile; required for FUNCTIONAL_OWNER_CLAIM",
    ),

    SlotId.WORD_CLASS_SLOT: SlotContract(
        slot_id=SlotId.WORD_CLASS_SLOT,
        serialized_id="WORD_CLASS_SLOT",
        sort=SlotSort.WORD_CLASS,
        stage="H6",
        semantic_purpose="Primary Arabic word class: ISM (noun), FI3L (verb), HARF (particle), OPERATOR, MABNI, MABNI_ISM, or other canonical class labels",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="UNKNOWN only when pipeline cannot determine word class; required for WORD_CLASS_CLAIM profile",
    ),

    # ── H7: Morphological ─────────────────────────────────────────────────────

    SlotId.INFLECTION_PREFIX_SLOT: SlotContract(
        slot_id=SlotId.INFLECTION_PREFIX_SLOT,
        serialized_id="INFLECTION_PREFIX_SLOT",
        sort=SlotSort.INFLECTIONAL,
        stage="H7",
        semantic_purpose="Inflectional prefix morpheme (e.g., imperfect verb person prefix ya-, ta-, na-, a-)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for past-tense verbs and nouns",
    ),

    SlotId.INFLECTION_SUFFIX_SLOT: SlotContract(
        slot_id=SlotId.INFLECTION_SUFFIX_SLOT,
        serialized_id="INFLECTION_SUFFIX_SLOT",
        sort=SlotSort.INFLECTIONAL,
        stage="H7",
        semantic_purpose="Inflectional suffix morpheme encoding person/number/gender agreement (e.g., -uu, -na, -ta, -tu)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for uninflected forms",
    ),

    SlotId.DERIVATIONAL_EXTENSION_SLOTS: SlotContract(
        slot_id=SlotId.DERIVATIONAL_EXTENSION_SLOTS,
        serialized_id="DERIVATIONAL_EXTENSION_SLOTS",
        sort=SlotSort.INFLECTIONAL,
        stage="H7",
        semantic_purpose="Derivational extension morphemes — extra material added by Form augmentation (e.g., Form IV hamza prefix, Form VII infixed nun)",
        value_type="tuple[str,...]",
        cardinality="MULTI",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for bare Form I; tuple of extension strings for augmented forms",
    ),

    SlotId.WEAK_RADICAL_SLOT: SlotContract(
        slot_id=SlotId.WEAK_RADICAL_SLOT,
        serialized_id="WEAK_RADICAL_SLOT",
        sort=SlotSort.INFLECTIONAL,
        stage="H7",
        semantic_purpose="Weak radical designation: identifies which radical position (R1, R2, R3) is weak (waw, ya, hamza, alif) and why it mutated in the surface",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for sound triliteral roots; set when weak radical detected",
    ),

    SlotId.GEMINATION_SLOT: SlotContract(
        slot_id=SlotId.GEMINATION_SLOT,
        serialized_id="GEMINATION_SLOT",
        sort=SlotSort.INFLECTIONAL,
        stage="H7",
        semantic_purpose="Gemination type and position: ROOT_GEMINATION (R2=R3), DERIVATIONAL_GEMINATION (Form augmentation), ASSIMILATION_GEMINATION (assimilation), or UNKNOWN_GEMINATION",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for non-geminated forms; uses GeminationType values",
    ),

    SlotId.RESTORATION_CANDIDATE_SET: SlotContract(
        slot_id=SlotId.RESTORATION_CANDIDATE_SET,
        serialized_id="RESTORATION_CANDIDATE_SET",
        sort=SlotSort.RADICAL,
        stage="H8",
        semantic_purpose="Candidate set for restored forms of deleted or mutated radicals (e.g., hollow root restoration, hamza restoration)",
        value_type="CandidateSet",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=True,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="AMBIGUOUS_CAPABLE",
        compatibility_notes="Optional slot; absence means no restoration needed",
    ),

    # ── H8-H9: Radical ────────────────────────────────────────────────────────

    SlotId.RADICAL_R1: SlotContract(
        slot_id=SlotId.RADICAL_R1,
        serialized_id="RADICAL_R1",
        sort=SlotSort.RADICAL,
        stage="H8",
        semantic_purpose="First radical (consonant) of the Arabic triliteral/quadriliteral root; UNKNOWN when root is ambiguous (multiple candidates)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline", "adapters"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="UNKNOWN when root_candidate is a list with >1 entries (T-10); NOT_APPLICABLE for closed boundaries",
    ),

    SlotId.RADICAL_R2: SlotContract(
        slot_id=SlotId.RADICAL_R2,
        serialized_id="RADICAL_R2",
        sort=SlotSort.RADICAL,
        stage="H8",
        semantic_purpose="Second radical (consonant) of the Arabic triliteral/quadriliteral root; UNKNOWN when root is ambiguous",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline", "adapters"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="UNKNOWN when root ambiguous; NOT_APPLICABLE for closed boundaries",
    ),

    SlotId.RADICAL_R3: SlotContract(
        slot_id=SlotId.RADICAL_R3,
        serialized_id="RADICAL_R3",
        sort=SlotSort.RADICAL,
        stage="H8",
        semantic_purpose="Third radical (consonant) of the Arabic triliteral root; UNKNOWN when root is ambiguous",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline", "adapters"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=True,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="UNKNOWN when root ambiguous; NOT_APPLICABLE for closed boundaries",
    ),

    SlotId.RADICAL_R4: SlotContract(
        slot_id=SlotId.RADICAL_R4,
        serialized_id="RADICAL_R4",
        sort=SlotSort.RADICAL,
        stage="H8",
        semantic_purpose="Fourth radical (consonant) for quadriliteral roots only; NOT_APPLICABLE for triliteral roots",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline", "adapters"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for the overwhelming majority of triliteral roots",
    ),

    SlotId.ROOT_CANDIDATE_SET: SlotContract(
        slot_id=SlotId.ROOT_CANDIDATE_SET,
        serialized_id="ROOT_CANDIDATE_SET",
        sort=SlotSort.RADICAL,
        stage="H9",
        semantic_purpose="Complete candidate set of root hypotheses when R1/R2/R3 are ambiguous; all candidates preserved with selected=None (T-10)",
        value_type="CandidateSet",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=True,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline", "adapters"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="AMBIGUOUS_CAPABLE",
        compatibility_notes="Only populated when root_candidate is a list >1; selected MUST be None (T-10)",
    ),

    # ── H10: Pattern ──────────────────────────────────────────────────────────

    SlotId.PATTERN_CANDIDATE_SET: SlotContract(
        slot_id=SlotId.PATTERN_CANDIDATE_SET,
        serialized_id="PATTERN_CANDIDATE_SET",
        sort=SlotSort.PATTERN,
        stage="H10",
        semantic_purpose="Wazn/pattern candidate set (e.g., فَعَلَ, فَاعِل, مَفْعُول); the morphological template governing consonant arrangement",
        value_type="CandidateSet",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=True,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="AMBIGUOUS_CAPABLE",
        compatibility_notes="UNKNOWN for closed-boundary tokens; AMBIGUOUS when multiple wazn candidates",
    ),

    SlotId.PATTERN_ALIGNMENT: SlotContract(
        slot_id=SlotId.PATTERN_ALIGNMENT,
        serialized_id="PATTERN_ALIGNMENT",
        sort=SlotSort.PATTERN,
        stage="H10",
        semantic_purpose="Alignment of the surface form's consonants against the selected wazn template (fa-ain-lam mapping)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
        compatibility_notes="Only meaningful when PATTERN_CANDIDATE_SET is FILLED",
    ),

    SlotId.PATTERN_EVIDENCE: SlotContract(
        slot_id=SlotId.PATTERN_EVIDENCE,
        serialized_id="PATTERN_EVIDENCE",
        sort=SlotSort.PATTERN,
        stage="H10",
        semantic_purpose="Evidence reference for the wazn/pattern assignment (e.g., WAZN_MATCH or LEXICAL catalog source)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
    ),

    # ── H11: Bab ──────────────────────────────────────────────────────────────

    SlotId.BAB_CANDIDATE_SET: SlotContract(
        slot_id=SlotId.BAB_CANDIDATE_SET,
        serialized_id="BAB_CANDIDATE_SET",
        sort=SlotSort.BAB,
        stage="H11",
        semantic_purpose="Verb conjugation class (bab): nasara/yanSuru, daraba/yaDribu, fatiha/yaftaHu, etc.; determines voweling of the imperfect and related inflected forms",
        value_type="CandidateSet",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=True,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="AMBIGUOUS_CAPABLE",
        compatibility_notes="UNKNOWN for non-verbs and functional tokens; AMBIGUOUS for multi-bab verbs",
    ),

    SlotId.MASDAR_CANDIDATE_SET: SlotContract(
        slot_id=SlotId.MASDAR_CANDIDATE_SET,
        serialized_id="MASDAR_CANDIDATE_SET",
        sort=SlotSort.MASDAR,
        stage="H12",
        semantic_purpose="Verbal noun (masdar) candidate set; the base nominal derivation from the root's Form I or augmented form",
        value_type="CandidateSet",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=True,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="AMBIGUOUS_CAPABLE",
        compatibility_notes="UNKNOWN for non-verbal roots; multiple masdar forms legal (SAMI_MASDAR residual)",
    ),

    SlotId.DERIVATIVE_CANDIDATE_SET: SlotContract(
        slot_id=SlotId.DERIVATIVE_CANDIDATE_SET,
        serialized_id="DERIVATIVE_CANDIDATE_SET",
        sort=SlotSort.DERIVATIVE,
        stage="H13",
        semantic_purpose="Derivative form type: ISM_FA3IL, ISM_MAF3UL, SIFA_MUSHABBAHA, MUBALGHA, ISM_ALA, ISM_MAKAN, ISM_ZAMAN, MIMI_MASDAR, NISBA",
        value_type="CandidateSet",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=True,
        provenance_required=False,
        evidence_required=True,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="AMBIGUOUS_CAPABLE",
        compatibility_notes="UNKNOWN for non-derivative forms; required for DERIVATIVE_CLAIM profile",
    ),

    # ── H14: Morphosyntax ─────────────────────────────────────────────────────

    SlotId.NUMBER_SLOT: SlotContract(
        slot_id=SlotId.NUMBER_SLOT,
        serialized_id="NUMBER_SLOT",
        sort=SlotSort.MORPHOSYNTAX,
        stage="H14",
        semantic_purpose="Grammatical number: SINGULAR, DUAL, PLURAL (sound masculine plural, sound feminine plural, broken plural)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="UNKNOWN for uninflected forms; UNKNOWN for functional tokens",
    ),

    SlotId.GENDER_SLOT: SlotContract(
        slot_id=SlotId.GENDER_SLOT,
        serialized_id="GENDER_SLOT",
        sort=SlotSort.MORPHOSYNTAX,
        stage="H14",
        semantic_purpose="Grammatical gender: MASCULINE or FEMININE",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="UNKNOWN for uninflected forms",
    ),

    SlotId.DEFINITENESS_SLOT: SlotContract(
        slot_id=SlotId.DEFINITENESS_SLOT,
        serialized_id="DEFINITENESS_SLOT",
        sort=SlotSort.MORPHOSYNTAX,
        stage="H14",
        semantic_purpose="Definiteness: DEFINITE (article present or proper noun) or INDEFINITE (tanwin or bare noun)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="CONDITIONAL",
        compatibility_notes="Derived from ARTICLE_SLOT when present; otherwise from pipeline output",
    ),

    SlotId.NISBA_SLOT: SlotContract(
        slot_id=SlotId.NISBA_SLOT,
        serialized_id="NISBA_SLOT",
        sort=SlotSort.MORPHOSYNTAX,
        stage="H14",
        semantic_purpose="Presence of the nisba (relational adjective) suffix -iyy-; indicates the word is a relational derivative",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE when no nisba suffix present",
    ),

    SlotId.COLLECTIVE_SLOT: SlotContract(
        slot_id=SlotId.COLLECTIVE_SLOT,
        serialized_id="COLLECTIVE_SLOT",
        sort=SlotSort.MORPHOSYNTAX,
        stage="H14",
        semantic_purpose="Collective noun marker — distinguishes mass noun (collective) base from unit noun (with ta marbuta suffix)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for most ISM; applicable for plant/fruit collective nouns",
    ),

    SlotId.UNIT_NOUN_SLOT: SlotContract(
        slot_id=SlotId.UNIT_NOUN_SLOT,
        serialized_id="UNIT_NOUN_SLOT",
        sort=SlotSort.MORPHOSYNTAX,
        stage="H14",
        semantic_purpose="Unit noun marker — identifies the singulative form derived from a collective by adding ta marbuta",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="CONDITIONAL",
        compatibility_notes="NOT_APPLICABLE for most ISM; companion to COLLECTIVE_SLOT",
    ),

    # ── H15: Lemma and Paradigm ───────────────────────────────────────────────

    SlotId.LEMMA_SLOT: SlotContract(
        slot_id=SlotId.LEMMA_SLOT,
        serialized_id="LEMMA_SLOT",
        sort=SlotSort.PARADIGM,
        stage="H15",
        semantic_purpose="Dictionary form (lemma) of the word — the canonical citation form used in Arabic lexicography (past 3rd masc. sing. for verbs, nom. sing. for nouns)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge", "tests"}),
        participates_in_claim_key=True,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="OPTIONAL",
    ),

    SlotId.PARADIGM_SLOT: SlotContract(
        slot_id=SlotId.PARADIGM_SLOT,
        serialized_id="PARADIGM_SLOT",
        sort=SlotSort.PARADIGM,
        stage="H15",
        semantic_purpose="Inflectional paradigm class ID — the complete specification of how the word inflects (verb form I-X, noun plural pattern, etc.)",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="STABLE",
        classification="OPTIONAL",
    ),

    SlotId.INFLECTIONAL_FAMILY_SLOT: SlotContract(
        slot_id=SlotId.INFLECTIONAL_FAMILY_SLOT,
        serialized_id="INFLECTIONAL_FAMILY_SLOT",
        sort=SlotSort.PARADIGM,
        stage="H15",
        semantic_purpose="Inflectional family grouping — clusters words sharing the same inflectional pattern across related roots",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
    ),

    SlotId.DERIVATIONAL_FAMILY_SLOT: SlotContract(
        slot_id=SlotId.DERIVATIONAL_FAMILY_SLOT,
        serialized_id="DERIVATIONAL_FAMILY_SLOT",
        sort=SlotSort.PARADIGM,
        stage="H15",
        semantic_purpose="Derivational family grouping — clusters all derivatives of the same root (masdar, ism fa3il, ism maf3ul, etc.) under a shared derivational family ID",
        value_type="str",
        cardinality="SINGLE",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=False,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"hokom_pipeline"}),
        valid_consumers=frozenset({"adapters", "bridge"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
    ),

    # ── Evidence / Residual ───────────────────────────────────────────────────

    SlotId.EVIDENCE_SLOT: SlotContract(
        slot_id=SlotId.EVIDENCE_SLOT,
        serialized_id="EVIDENCE_SLOT",
        sort=SlotSort.EVIDENCE,
        stage="EVIDENCE",
        semantic_purpose="Aggregate evidence container — holds the full set of EvidenceReference records gathered during this evaluation run",
        value_type="tuple[EvidenceReference,...]",
        cardinality="MULTI",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"adapters", "bridge"}),
        valid_consumers=frozenset({"bridge", "tests"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
        compatibility_notes="Not a TypedSlot in the current build — conceptual slot for evidence aggregation",
    ),

    SlotId.RESIDUAL_SLOT: SlotContract(
        slot_id=SlotId.RESIDUAL_SLOT,
        serialized_id="RESIDUAL_SLOT",
        sort=SlotSort.RESIDUAL,
        stage="RESIDUAL",
        semantic_purpose="Aggregate residual container — holds the full set of HokomResidualRecord entries accumulated during this evaluation run",
        value_type="tuple[HokomResidualRecord,...]",
        cardinality="MULTI",
        nullable=True,
        absence_legal=True,
        multi_valued_legal=True,
        ambiguity_legal=False,
        provenance_required=False,
        evidence_required=False,
        valid_producers=frozenset({"adapters", "bridge"}),
        valid_consumers=frozenset({"bridge", "tests"}),
        participates_in_claim_key=False,
        participates_in_eval_identity=False,
        stability="PROVISIONAL",
        classification="OPTIONAL",
        compatibility_notes="Not a TypedSlot in the current build — conceptual slot for residual aggregation",
    ),
}


def validate_registry() -> list[str]:
    """Return list of violations. Empty = registry is consistent."""
    violations = []
    seen_serialized: dict[str, SlotId] = {}

    for slot_id, contract in SLOT_REGISTRY.items():
        # serialized_id must equal slot_id.value
        if contract.serialized_id != slot_id.value:
            violations.append(f"SERIALIZED_ID_MISMATCH: {slot_id} → {contract.serialized_id!r}")
        # no duplicate serialized IDs
        if contract.serialized_id in seen_serialized:
            violations.append(
                f"DUPLICATE_SERIALIZED_ID: {contract.serialized_id} "
                f"(first={seen_serialized[contract.serialized_id]}, second={slot_id})"
            )
        seen_serialized[contract.serialized_id] = slot_id

        # ambiguity_legal implies multi_valued_legal
        if contract.ambiguity_legal and not contract.multi_valued_legal:
            violations.append(
                f"AMBIGUITY_WITHOUT_MULTI_VALUED: {slot_id} — "
                "ambiguity_legal=True requires multi_valued_legal=True"
            )

        # REQUIRED slots must not have absence_legal unless RESERVED
        if contract.classification == "REQUIRED" and contract.absence_legal and contract.stability != "RESERVED":
            violations.append(
                f"REQUIRED_SLOT_ABSENCE_LEGAL: {slot_id} — "
                "REQUIRED classification but absence_legal=True"
            )

    # every SlotId must have an entry
    for slot_id in SlotId:
        if slot_id not in SLOT_REGISTRY:
            violations.append(f"UNREGISTERED_SLOT_ID: {slot_id}")

    return violations


__all__ = ["SlotContract", "SLOT_REGISTRY", "validate_registry"]
