"""
Ayat al-Dayn Canonical Lexical Registry — E1

Source: reports/ayat_al_dayn_demo/ayat_al_dayn_results.csv
Corpus: البقرة 2:282 — 129 unique tokens
Corpus SHA256: 6bd635a05530965f13f76cf003f7738130badec6981bcb0e73f2465d386e1ed7
VENDOR_SHA: bc9d1ea5ef45970f5f3ec132441e30fd54b3da52

Registry: 74 unique ISM/FI3L host surfaces
  LICENSED (no blocking residuals): 62 entries
  With residuals (DEFERRED/PIPELINE_DEFER): 12 entries
  HARF (NOT_APPLICABLE): 21 tokens — no registry entries
  Empty word class (DEFERRED): 21 tokens — no registry entries

Constitutional notes:
  - RegistryEntry.non_meaning_proof is structural ONLY (no semantic meaning)
  - Root letters are phonological/morphological identity, not meaning
  - domain = DAL_ONLY for all ISM/FI3L entries (pre-semantic DAL domain)
  - rank = CANDIDATE for all entries (no rank promotion in E1)
  - HARF tokens have no registry entries (not in DAL_ONLY domain)
  - This registry is the E1 deliverable, consumed by E2 (P2 projection)

Phase: E1 — AYAT-AL-DAYN CANONICAL LEXICAL REGISTRY
Next phase consumer: E2 → registry_adapter.py → P2_REGISTRY_PROJECTION
"""
from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]
_VENDOR_PATH = _REPO_ROOT / "vendor" / "Taaqol-GPT" / "src"
_VENDOR_SHA = "bc9d1ea5ef45970f5f3ec132441e30fd54b3da52"
_CORPUS_SHA = "6bd635a05530965f13f76cf003f7738130badec6981bcb0e73f2465d386e1ed7"

# ── Fail-closed vendor import ────────────────────────────────────────────────
_REGISTRY_CONTRACT_AVAILABLE = False
try:
    _vs = str(_VENDOR_PATH)
    if _vs not in sys.path:
        sys.path.insert(0, _vs)
    from taaqqul_slot_geometry.weight.registry_contract import (  # type: ignore
        RegistryEntry as _RegistryEntry,
        RegistryDomain as _RegistryDomain,
        REGISTRY_RANK_CEILING as _REGISTRY_RANK_CEILING,
    )
    from taaqqul_slot_geometry.core.rank_lattice import Rank as _Rank  # type: ignore
    _REGISTRY_CONTRACT_AVAILABLE = True
except ImportError:
    pass


# ── Raw registry data (Python 3.10 compatible — no vendor types) ─────────────
# Each entry: key=host_surface, structural proof, no semantic meaning assigned.
# Used as input to build_ayat_al_dayn_registry() on Python 3.12+.
_REGISTRY_RAW: tuple[dict, ...] = (
    {
        "key": 'الَّذِينَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:RELATIVE | root_state:UNKNOWN',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_UNKNOWN', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:3:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'UNKNOWN',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'ءَمَنُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3ALA | form:FORM_IV | class:FI3L | sub:VERBAL_PAST | root_state:KNOWN | root:ءمن',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:4:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'ءمن',
        "wazn": 'FA3ALA',
    },
    {
        "key": 'تَدَايَنْتُمْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:تَفَاعَلَ | form:FORM_VI | class:FI3L | sub:VERBAL_PAST | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:6:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'تَفَاعَلَ',
    },
    {
        "key": 'دَيْنٍ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3L | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:دين',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:7:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'دين',
        "wazn": 'FA3L',
    },
    {
        "key": 'أَجَلٍ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA_A_LA | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:ءجل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:9:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'ءجل',
        "wazn": 'FA_A_LA',
    },
    {
        "key": 'مُسَمًّى',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:10:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'اكْتُبُو',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:فَعَلَ | form:FORM_I | class:FI3L | sub:VERBAL_IMPERATIVE | root_state:KNOWN | root:كتب',
        "rank": "CANDIDATE",
        "residuals": ['PIPELINE_DEFER', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:11:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'كتب',
        "wazn": 'فَعَلَ',
    },
    {
        "key": 'يَكْتُبْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:12:ayat_al_dayn:2:282|corpus:24:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'بَيْنَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3L | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:بين',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:13:ayat_al_dayn:2:282|corpus:103:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'بين',
        "wazn": 'FA3L',
    },
    {
        "key": 'كَاتِبٌ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3IL | form:FA3IL_PARTICIPLE | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:كتب',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:14:ayat_al_dayn:2:282|corpus:18:ayat_al_dayn:2:282|corpus:114:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'كتب',
        "wazn": 'FA3IL',
    },
    {
        "key": 'عَدْلِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3L | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:عدل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:15:ayat_al_dayn:2:282|corpus:52:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'عدل',
        "wazn": 'FA3L',
    },
    {
        "key": 'يَأْبَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:17:ayat_al_dayn:2:282|corpus:74:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'يَكْتُبَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:كتب',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:20:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'كتب',
        "wazn": '',
    },
    {
        "key": 'عَلَّمَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA33ALA | form:FORM_II | class:FI3L | sub:VERBAL_PAST | root_state:KNOWN | root:علم',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:22:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'علم',
        "wazn": 'FA33ALA',
    },
    {
        "key": 'يُمْلِلِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:25:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'الَّذِي',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:RELATIVE | root_state:UNKNOWN',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_UNKNOWN', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:26:ayat_al_dayn:2:282|corpus:38:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'UNKNOWN',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'عَلَيْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:27:ayat_al_dayn:2:282|corpus:39:ayat_al_dayn:2:282|corpus:105:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'حَقُّ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA_A_LA | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:حقق',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:28:ayat_al_dayn:2:282|corpus:40:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'حقق',
        "wazn": 'FA_A_LA',
    },
    {
        "key": 'يَتَّقِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:اِفْتَعَلَ | form:FORM_VIII | class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:29:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'اِفْتَعَلَ',
    },
    {
        "key": 'يَبْخَسْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:بخس',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:33:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'بخس',
        "wazn": '',
    },
    {
        "key": 'شَيْئًا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3L | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:شيء',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:35:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'شيء',
        "wazn": 'FA3L',
    },
    {
        "key": 'كَانَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:FI3L | sub:VERBAL_PAST | root_state:UNKNOWN',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_UNKNOWN'],
        "trace_ref": 'corpus:37:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'UNKNOWN',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'سَفِيهًا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:41:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'ضَعِيفًا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:43:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'يَسْتَطِيعُ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:ISTAF3ALA | form:FORM_X | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:طيع',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:46:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'طيع',
        "wazn": 'ISTAF3ALA',
    },
    {
        "key": 'يُمِلَّ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:AF3AL | form:FORM_IV | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:ملل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:48:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'ملل',
        "wazn": 'AF3AL',
    },
    {
        "key": 'هُوَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:PRONOUN | root_state:UNKNOWN',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_UNKNOWN', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:49:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'UNKNOWN',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'يُمْلِلْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:50:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'وَلِيُّ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:51:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'اسْتَشْهِدُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:ISTAF3ALA | form:FORM_X | class:FI3L | sub:VERBAL_IMPERATIVE | root_state:KNOWN | root:شهد',
        "rank": "CANDIDATE",
        "residuals": ['PIPELINE_DEFER', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:53:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'شهد',
        "wazn": 'ISTAF3ALA',
    },
    {
        "key": 'شَهِيدَيْنِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:54:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'رِجَالِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:56:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'يَكُونَا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:59:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'رَجُلَيْنِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:60:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'رَجُلٌ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA_U_LA | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:رجل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:61:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'رجل',
        "wazn": 'FA_U_LA',
    },
    {
        "key": 'امْرَأَتَانِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:فَعَلَ | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['PIPELINE_DEFER', 'ROOT_DEFERRED', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:62:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'فَعَلَ',
    },
    {
        "key": 'مِمَّنْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:63:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'تَرْضَوْنَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:64:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'شُّهَدَاءِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['PIPELINE_DEFER', 'ROOT_DEFERRED', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:66:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'تَضِلَّ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:ضلل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:68:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'ضلل',
        "wazn": '',
    },
    {
        "key": 'إِحْدَا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:أَفْعَلَ | form:FORM_IV | class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:69:ayat_al_dayn:2:282|corpus:71:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'أَفْعَلَ',
    },
    {
        "key": 'تُذَكِّرَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA33ALA | form:FORM_II | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:ذكر',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:70:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'ذكر',
        "wazn": 'FA33ALA',
    },
    {
        "key": 'أُخْرَى',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:أَفْعَلَ | form:FORM_IV | class:ISM | sub:LEXICAL_NOUN | root_state:UNKNOWN',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_UNKNOWN', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:72:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'UNKNOWN',
        "root": '',
        "wazn": 'أَفْعَلَ',
    },
    {
        "key": 'شُّهَدَاءُ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['PIPELINE_DEFER', 'ROOT_DEFERRED', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:75:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'دُعُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:AMBIGUOUS',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_AMBIGUOUS'],
        "trace_ref": 'corpus:78:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'AMBIGUOUS',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'تَسْأَمُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:سءم',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:80:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'سءم',
        "wazn": '',
    },
    {
        "key": 'تَكْتُبُو',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:كتب',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:82:ayat_al_dayn:2:282|corpus:108:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'كتب',
        "wazn": '',
    },
    {
        "key": 'صَغِيرًا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:83:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'كَبِيرًا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:85:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'أَجَلِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA_A_LA | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:ءجل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:87:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'ءجل',
        "wazn": 'FA_A_LA',
    },
    {
        "key": 'ذَلِكُمْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:88:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'أَقْسَطُ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:AF3AL | form:FORM_IV | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:قسط',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:89:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'قسط',
        "wazn": 'AF3AL',
    },
    {
        "key": 'عِنْدَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FI3L | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:عند',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:90:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'عند',
        "wazn": 'FI3L',
    },
    {
        "key": 'أَقْوَمُ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:أَفْعَلَ | form:FORM_IV | class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:92:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'أَفْعَلَ',
    },
    {
        "key": 'شَّهَادَةِ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['PIPELINE_DEFER', 'ROOT_DEFERRED', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:93:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'أَدْنَى',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:أَفْعَلَ | form:FORM_IV | class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:94:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'أَفْعَلَ',
    },
    {
        "key": 'أَلَّا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:اِفْتَعَلَ | form:FORM_VIII | class:ISM | sub:LEXICAL_NOUN | root_state:UNKNOWN',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_UNKNOWN', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:95:ayat_al_dayn:2:282|corpus:107:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'UNKNOWN',
        "root": '',
        "wazn": 'اِفْتَعَلَ',
    },
    {
        "key": 'تَرْتَابُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:اِفْتَعَلَ | form:FORM_VIII | class:FI3L | sub:VERBAL_IMPERFECT | root_state:UNKNOWN',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_UNKNOWN'],
        "trace_ref": 'corpus:96:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'UNKNOWN',
        "root": '',
        "wazn": 'اِفْتَعَلَ',
    },
    {
        "key": 'تَكُونَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:99:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'تِجَارَةً',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3ALA | form:FORM_III | class:ISM | sub:MASDAR | root_state:KNOWN | root:جرة',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:100:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'جرة',
        "wazn": 'FA3ALA',
    },
    {
        "key": 'حَاضِرَةً',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3IL | form:FA3IL_PARTICIPLE | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:حضر',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:101:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'حضر',
        "wazn": 'FA3IL',
    },
    {
        "key": 'تُدِيرُونَ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:أَفْعَلَ | form:FORM_IV | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:دور',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:102:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'دور',
        "wazn": 'أَفْعَلَ',
    },
    {
        "key": 'جُنَاحٌ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:106:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'أَشْهِدُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:AF3AL | form:FORM_IV | class:FI3L | sub:VERBAL_IMPERATIVE | root_state:KNOWN | root:شهد',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:109:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'شهد',
        "wazn": 'AF3AL',
    },
    {
        "key": 'تَبَايَعْتُمْ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:تَفَاعَلَ | form:FORM_VI | class:FI3L | sub:VERBAL_PAST | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:111:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'تَفَاعَلَ',
    },
    {
        "key": 'يُضَارَّ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:113:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'شَهِيدٌ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:116:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'تَفْعَلُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: form:FORM_I_IMPERFECT | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:فعل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:118:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'فعل',
        "wazn": '',
    },
    {
        "key": 'فُسُوقٌ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:120:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
    {
        "key": 'اتَّقُوا',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:اِفْتَعَلَ | form:FORM_VIII | class:FI3L | sub:VERBAL_IMPERATIVE | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['PIPELINE_DEFER', 'ROOT_DEFERRED', 'TAAQOL_DEFERRED'],
        "trace_ref": 'corpus:122:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": 'اِفْتَعَلَ',
    },
    {
        "key": 'يُعَلِّمُ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA33ALA | form:FORM_II | class:FI3L | sub:VERBAL_IMPERFECT | root_state:KNOWN | root:علم',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:124:ayat_al_dayn:2:282',
        "wc": 'FI3L',
        "root_state": 'KNOWN',
        "root": 'علم',
        "wazn": 'FA33ALA',
    },
    {
        "key": 'كُلِّ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:فَعَلَ | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:كلل',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:127:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'كلل',
        "wazn": 'فَعَلَ',
    },
    {
        "key": 'شَيْءٍ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: wazn:FA3L | form:FORM_I | class:ISM | sub:LEXICAL_NOUN | root_state:KNOWN | root:شيء',
        "rank": "CANDIDATE",
        "residuals": [],
        "trace_ref": 'corpus:128:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'KNOWN',
        "root": 'شيء',
        "wazn": 'FA3L',
    },
    {
        "key": 'عَلِيمٌ',
        "domain": "DAL_ONLY",
        "non_meaning_proof": 'structural pre-semantic host carrier: class:ISM | sub:LEXICAL_NOUN | root_state:DEFERRED',
        "rank": "CANDIDATE",
        "residuals": ['ROOT_DEFERRED'],
        "trace_ref": 'corpus:129:ayat_al_dayn:2:282',
        "wc": 'ISM',
        "root_state": 'DEFERRED',
        "root": '',
        "wazn": '',
    },
)


def build_ayat_al_dayn_registry() -> tuple:
    """
    Build the canonical Ayat al-Dayn registry as a tuple of RegistryEntry objects.

    Returns empty tuple if vendor not available (Python 3.10 / import failure).
    This is the E1 build function — called once at module import.

    Constitutional invariants:
    - All entries have non_meaning_proof (structural, not semantic)
    - All entries have rank = CANDIDATE (no rank promotion in E1)
    - All entries have domain = DAL_ONLY
    - HARF tokens have no entries (not in DAL_ONLY domain)
    - registry_contract validates structural invariants at birth
    """
    if not _REGISTRY_CONTRACT_AVAILABLE:
        return ()

    built = []
    for raw in _REGISTRY_RAW:
        try:
            entry = _RegistryEntry(
                key=raw["key"],
                domain=_RegistryDomain("DAL_ONLY"),
                non_meaning_proof=raw["non_meaning_proof"],
                rank=_Rank.CANDIDATE,
                residuals=(),
                trace_ref=raw["trace_ref"],
            )
            built.append(entry)
        except Exception as e:
            # Fail-closed: malformed entry → skip, log as residual
            _REGISTRY_BUILD_FAILURES.append({
                "key": raw.get("key", "UNKNOWN"),
                "error": str(e),
            })
    return tuple(built)


# ── Build the registry at import time ────────────────────────────────────────
_REGISTRY_BUILD_FAILURES: list[dict] = []
AYAT_AL_DAYN_REGISTRY: tuple = build_ayat_al_dayn_registry()

# ── Module invariants ────────────────────────────────────────────────────────
REGISTRY_SIZE = len(_REGISTRY_RAW)         # 74 unique host surfaces
BUILT_SIZE = len(AYAT_AL_DAYN_REGISTRY)    # 74 on Python 3.12+, 0 on 3.10
BUILD_FAILURES: list = _REGISTRY_BUILD_FAILURES  # list of failure dicts ([] = all good)
BUILD_FAILURE_COUNT: int = len(_REGISTRY_BUILD_FAILURES)

# ── Public constants ──────────────────────────────────────────────────────────
# CORPUS_SHA and VENDOR_SHA are public aliases for constitutional verification.
CORPUS_SHA: str = _CORPUS_SHA   # G_E1_08: corpus SHA embedded in module
VENDOR_SHA: str = _VENDOR_SHA   # constitutional VENDOR_SHA pinned constant

__all__ = [
    "AYAT_AL_DAYN_REGISTRY",
    "BUILD_FAILURES",
    "BUILD_FAILURE_COUNT",
    "BUILT_SIZE",
    "CORPUS_SHA",
    "REGISTRY_SIZE",
    "VENDOR_SHA",
    "_CORPUS_SHA",
    "_REGISTRY_CONTRACT_AVAILABLE",
    "_REGISTRY_RAW",
    "_VENDOR_SHA",
    "build_ayat_al_dayn_registry",
]