"""
Governance: canonical report artifacts must be bound to the audited HEAD.

Contract (non-self-referential):
    The latest closure manifest records the HEAD (manifest.commit) at which
    the canonical audit was run.  The binding is valid as long as no canonical
    artifact file has been modified since that commit.

    Governance-only commits (runner, shell tests) that do NOT touch
    reports/ayat_al_dayn_demo/ are explicitly permitted after an audit and
    must NOT invalidate the binding.

    The binding is invalidated only when a canonical artifact file is modified
    after the last audit commit — which would require re-running the full
    canonical audit and generating a fresh manifest.

AUDITED_ARTIFACT_HEAD = 2e2a3ac71a00ad520675c91e13904903f573034b
CANONICAL_CSV_SHA     = 5e673089f33e42309a66ded1816fffb9098227f1f86bb35c5faa33349dd47d84
"""
import json
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# The last commit that generated the canonical artifacts. Manifests written
# before this commit predate the artifacts and are treated as "no binding yet".
AUDITED_ARTIFACT_HEAD = '2e2a3ac71a00ad520675c91e13904903f573034b'

# Canonical artifact directory — the only files whose modification invalidates
# the audit binding.
CANONICAL_ARTIFACT_DIR = 'reports/ayat_al_dayn_demo/'


def test_no_stale_report_artifacts():
    """
    The latest closure manifest must have been written at a commit from which
    no canonical artifact file has subsequently changed.

    Governance-only commits (scripts/run_canonical_final_audit.sh,
    tests/shell/test_audit_runner.sh, etc.) that do not touch
    reports/ayat_al_dayn_demo/ are permitted after the audit and pass this test.

    If this fails because an artifact genuinely changed, re-run the full
    canonical audit: bash scripts/run_canonical_final_audit.sh
    """
    gate_dir = REPO_ROOT / 'reports' / 'canonical_gate'
    if not gate_dir.exists():
        return  # No gate reports yet — not a failure at this stage

    manifests = list(gate_dir.rglob('closure_manifest.*.json'))
    if not manifests:
        return  # No manifests yet — governance infrastructure just established

    latest = sorted(manifests, key=lambda p: p.stat().st_mtime)[-1]
    data = json.loads(latest.read_text(encoding='utf-8'))
    manifest_commit = data.get('commit', '')

    assert manifest_commit, (
        f"Closure manifest {latest.name} is missing the 'commit' field."
    )

    # Use full hash for ancestry check if available.
    manifest_commit_full = data.get('commit_full', manifest_commit)

    # A manifest written before the canonical artifact generation is not a valid
    # artifact binding — it predates the artifacts it would claim to cover.
    # Treat such manifests as "no valid manifest yet"; return without failure.
    # This is correct: the first valid manifest is generated by the full canonical
    # audit after the artifacts were committed.
    is_post_artifact = subprocess.run(
        ['git', 'merge-base', '--is-ancestor',
         AUDITED_ARTIFACT_HEAD, manifest_commit_full],
        capture_output=True, cwd=REPO_ROOT
    ).returncode == 0

    if not is_post_artifact:
        return  # manifest predates artifact generation — no valid binding to check

    # The manifest was written after the artifacts were generated.
    # Check whether any canonical artifact file changed since the audit commit.
    # Governance-only changes (runner, tests) never touch this directory,
    # so the diff will be empty for every governance-only commit.
    diff_result = subprocess.run(
        ['git', 'diff', '--name-only',
         f'{manifest_commit}..HEAD', '--',
         CANONICAL_ARTIFACT_DIR],
        capture_output=True, text=True, cwd=REPO_ROOT
    )
    changed = diff_result.stdout.strip()

    assert not changed, (
        f"Canonical artifacts changed since audit (manifest.commit={manifest_commit!r}).\n"
        f"Changed files since {manifest_commit}:\n{changed}\n"
        f"Re-run the full canonical audit: bash scripts/run_canonical_final_audit.sh"
    )


def test_audited_artifact_head_immutable():
    """
    The declared AUDITED_ARTIFACT_HEAD must match the last commit that
    actually touched the canonical artifact files.  This proves the
    binding is anchored to a real linguistic commit, not an arbitrary hash.
    """
    result = subprocess.run(
        ['git', 'log', '--follow', '-1', '--format=%H', '--',
         CANONICAL_ARTIFACT_DIR],
        capture_output=True, text=True, cwd=REPO_ROOT
    )
    actual_head = result.stdout.strip()

    assert actual_head == AUDITED_ARTIFACT_HEAD, (
        f"AUDITED_ARTIFACT_HEAD mismatch: declared={AUDITED_ARTIFACT_HEAD!r}, "
        f"actual last artifact commit={actual_head!r}. "
        f"If artifacts were intentionally regenerated, update AUDITED_ARTIFACT_HEAD."
    )
