"""
saleh_snapshot.py — immutable provenance snapshot of the Saleh/Qiyas
19-stage SCG registry.

Loading strategy (fail-closed):
    1. Load data/canonical_19_stage_registry.json (generated by
       scripts/generate_canonical_registry_snapshot.py).
    2. If not found, raise RegistrySnapshotMissing with instructions.
    3. Validate: exactly 19 layers, all IMPLEMENTED, P12 TERMINAL, no P13.

Ownership boundary (binding):
    This module is a READ-ONLY consumer of Saleh/Qiyas. It NEVER imports
    Saleh at runtime (only the generator script does). It NEVER mutates
    the snapshot JSON. It provides typed, immutable accessors only.
"""
from __future__ import annotations

import json
import warnings
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

# ── canonical layer ID list (verbatim from master_registry_seed.py §4.2) ──────
CANONICAL_LAYER_IDS: tuple[str, ...] = (
    "P0_UNICODE_CANDIDATE",
    "P0_TYPED_CODEPOINT",
    "P0_GLYPH_CLASSIFICATION",
    "P1_LETTER_IDENTITY_CARRIER",
    "P1_HARAKA_MARK_IDENTITY_CARRIER",
    "P1_CONDITIONED_TYPED_SEQUENCE",
    "P1_POSITION_CARRIER",
    "P1_SLOT_CANDIDATE",
    "P2_REGISTRY_PROJECTION",
    "P3_ROOT_STEM_CLOSURE",
    "P4_JAMID_MUSHTAQ",
    "P5_MUFRAD_WORD_CONTRACTS",
    "P6_VERBAL_SIGNIFIED_ALONE",
    "P7_COMPOSITION_READINESS",
    "P8_AMIL_MAMUL",
    "P9_SENTENCE_GEOMETRY",
    "P10_RELATION_GEOMETRY",
    "P11_IRAB_GEOMETRY",
    "P12_IFADAH_SPEECH_FORCE",
)

_EXPECTED_COUNT = 19
_TERMINAL_LAYER_ID = "P12_IFADAH_SPEECH_FORCE"

# ── snapshot file discovery ────────────────────────────────────────────────────
def _find_snapshot_path() -> Path:
    """Locate data/canonical_19_stage_registry.json relative to hokom root."""
    # Walk up from this file to find pyproject.toml (hokom root marker)
    candidate = Path(__file__).resolve()
    for _ in range(8):
        candidate = candidate.parent
        if (candidate / "pyproject.toml").exists():
            return candidate / "data" / "canonical_19_stage_registry.json"
    # Fallback: relative to CWD
    return Path("data") / "canonical_19_stage_registry.json"


# ── data classes ──────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ProvenanceRecord:
    saleh_commit_sha: str
    saleh_src_path: str
    generation_function: str
    registry_digest: str
    generator_script: str


@dataclass(frozen=True)
class LayerEntry:
    """Typed, immutable view of one layer from the snapshot."""
    id: str
    name: str
    phase: str
    status: str          # "implemented" in a complete registry
    ordinal: int
    is_terminal: bool

    origin_layer_id: str
    origin_output_type: str
    branch_output_type: str
    branch_reason: str

    shared_cause: str
    conditions: tuple[str, ...]
    blockers: tuple[str, ...]
    invalidating_differences: tuple[str, ...]

    target_boundary_closes: tuple[str, ...]
    target_boundary_opens: tuple[str, ...]    # () for P12 (TERMINAL)

    forbidden_outputs: tuple[str, ...]
    minimum_required_fields: tuple[str, ...]

    preserves_ids: tuple[str, ...]
    allowed_changes: tuple[str, ...]
    forbidden_changes: tuple[str, ...]

    allowed_previous_layer_ids: tuple[str, ...]
    allowed_next_layer_ids: tuple[str, ...]
    forbidden_direct_next_layer_ids: tuple[str, ...]


@dataclass(frozen=True)
class RegistrySnapshot:
    """Complete 19-stage registry snapshot with provenance."""
    provenance: ProvenanceRecord
    schema_version: str
    layer_count: int
    terminal_layer_id: str
    no_layer_after_p12: bool
    canonical_order: tuple[str, ...]
    _layers_by_id: dict[str, LayerEntry]

    def get_layer(self, layer_id: str) -> LayerEntry:
        if layer_id not in self._layers_by_id:
            raise KeyError(
                f"Layer '{layer_id}' not in canonical registry snapshot. "
                f"Known IDs: {list(self._layers_by_id)}"
            )
        return self._layers_by_id[layer_id]

    def layers_in_order(self) -> tuple[LayerEntry, ...]:
        return tuple(self._layers_by_id[lid] for lid in self.canonical_order)

    def assert_no_p13(self) -> None:
        """Raise AssertionError if any post-P12 layer is found."""
        terminal = self._layers_by_id[self.terminal_layer_id]
        assert terminal.target_boundary_opens == (), (
            f"TERMINAL layer {self.terminal_layer_id} must have "
            "target_boundary_opens==() but got: "
            f"{terminal.target_boundary_opens}"
        )
        assert self.no_layer_after_p12, "no_layer_after_p12 must be True"
        assert self.layer_count == _EXPECTED_COUNT, (
            f"Expected {_EXPECTED_COUNT} layers, got {self.layer_count}"
        )


# ── exceptions ────────────────────────────────────────────────────────────────

class RegistrySnapshotMissing(RuntimeError):
    """Raised when the snapshot JSON has not been generated yet."""

    def __init__(self, path: Path) -> None:
        super().__init__(
            f"Canonical registry snapshot not found at {path}.\n"
            "Generate it with:\n"
            "    cd <hokom-root>\n"
            "    PYTHONPATH=src:vendor/Taaqol-GPT/src"
            ":../fractal/algebra/Saleh-/src \\\n"
            "        python scripts/generate_canonical_registry_snapshot.py\n"
            "Then re-run."
        )


class RegistrySnapshotInvalid(RuntimeError):
    """Raised when the snapshot JSON fails structural validation."""
    pass


# ── loader ────────────────────────────────────────────────────────────────────

def _parse_layer(raw: dict) -> LayerEntry:
    def _t(v: list) -> tuple[str, ...]:
        return tuple(v) if v else ()

    return LayerEntry(
        id=raw["id"],
        name=raw["name"],
        phase=raw["phase"],
        status=raw["status"],
        ordinal=raw["ordinal"],
        is_terminal=raw["is_terminal"],
        origin_layer_id=raw["origin_layer_id"],
        origin_output_type=raw["origin_output_type"],
        branch_output_type=raw["branch_output_type"],
        branch_reason=raw["branch_reason"],
        shared_cause=raw["shared_cause"],
        conditions=_t(raw.get("conditions", [])),
        blockers=_t(raw.get("blockers", [])),
        invalidating_differences=_t(raw.get("invalidating_differences", [])),
        target_boundary_closes=_t(raw.get("target_boundary_closes", [])),
        target_boundary_opens=_t(raw.get("target_boundary_opens", [])),
        forbidden_outputs=_t(raw.get("forbidden_outputs", [])),
        minimum_required_fields=_t(raw.get("minimum_required_fields", [])),
        preserves_ids=_t(raw.get("preserves_ids", [])),
        allowed_changes=_t(raw.get("allowed_changes", [])),
        forbidden_changes=_t(raw.get("forbidden_changes", [])),
        allowed_previous_layer_ids=_t(raw.get("allowed_previous_layer_ids", [])),
        allowed_next_layer_ids=_t(raw.get("allowed_next_layer_ids", [])),
        forbidden_direct_next_layer_ids=_t(
            raw.get("forbidden_direct_next_layer_ids", [])
        ),
    )


def _validate(snapshot: RegistrySnapshot, path: Path) -> None:
    """Structural validation of the loaded snapshot."""
    errors: list[str] = []

    # Layer count
    if snapshot.layer_count != _EXPECTED_COUNT:
        errors.append(
            f"Expected {_EXPECTED_COUNT} layers, got {snapshot.layer_count}"
        )

    # Canonical order completeness
    missing_ids = set(CANONICAL_LAYER_IDS) - set(snapshot.canonical_order)
    if missing_ids:
        errors.append(f"Canonical order missing layers: {sorted(missing_ids)}")

    extra_ids = set(snapshot.canonical_order) - set(CANONICAL_LAYER_IDS)
    if extra_ids:
        errors.append(f"Canonical order has unexpected layers: {sorted(extra_ids)}")

    # All layers IMPLEMENTED
    non_impl = [
        l.id for l in snapshot.layers_in_order()
        if l.status != "implemented"
    ]
    if non_impl:
        errors.append(f"Non-implemented layers in snapshot: {non_impl}")

    # P12 terminal
    try:
        p12 = snapshot.get_layer(_TERMINAL_LAYER_ID)
        if not p12.is_terminal:
            errors.append(f"{_TERMINAL_LAYER_ID} must be terminal (is_terminal=True)")
        if p12.target_boundary_opens != ():
            errors.append(
                f"{_TERMINAL_LAYER_ID}.target_boundary_opens must be () "
                f"(got {p12.target_boundary_opens})"
            )
    except KeyError:
        errors.append(f"Terminal layer {_TERMINAL_LAYER_ID} not found in snapshot")

    # no_layer_after_p12 flag
    if not snapshot.no_layer_after_p12:
        errors.append("no_layer_after_p12 must be True")

    # Absolute forbidden outputs in every layer
    _absolute = {"HukmCandidate", "RealityClaim", "FinalMeaning"}
    for layer in snapshot.layers_in_order():
        missing_forbidden = _absolute - set(layer.forbidden_outputs)
        if missing_forbidden:
            errors.append(
                f"Layer {layer.id} missing absolute forbidden outputs: "
                f"{missing_forbidden}"
            )

    if errors:
        raise RegistrySnapshotInvalid(
            f"Snapshot at {path} failed validation:\n"
            + "\n".join(f"  • {e}" for e in errors)
        )


@lru_cache(maxsize=1)
def load_snapshot(snapshot_path: str | None = None) -> RegistrySnapshot:
    """
    Load and validate the canonical 19-stage registry snapshot.

    Parameters
    ----------
    snapshot_path : str | None
        Explicit path to the JSON file. If None, auto-discovers
        data/canonical_19_stage_registry.json from the hokom root.

    Returns
    -------
    RegistrySnapshot
        Validated, immutable snapshot (LRU-cached after first load).

    Raises
    ------
    RegistrySnapshotMissing
        If the JSON file does not exist.
    RegistrySnapshotInvalid
        If the JSON fails structural validation.
    """
    path = Path(snapshot_path) if snapshot_path else _find_snapshot_path()

    if not path.exists():
        raise RegistrySnapshotMissing(path)

    raw = json.loads(path.read_text(encoding="utf-8"))

    prov_raw = raw.get("provenance", {})
    provenance = ProvenanceRecord(
        saleh_commit_sha=prov_raw.get("saleh_commit_sha", "unknown"),
        saleh_src_path=prov_raw.get("saleh_src_path", ""),
        generation_function=prov_raw.get("generation_function", ""),
        registry_digest=prov_raw.get("registry_digest", ""),
        generator_script=prov_raw.get("generator_script", ""),
    )

    layers_list: list[LayerEntry] = [
        _parse_layer(l) for l in raw.get("layers", [])
    ]
    layers_by_id: dict[str, LayerEntry] = {l.id: l for l in layers_list}

    canonical_order_raw: list[str] = raw.get("canonical_order", [])

    snapshot = RegistrySnapshot(
        provenance=provenance,
        schema_version=raw.get("schema_version", "unknown"),
        layer_count=raw.get("layer_count", len(layers_list)),
        terminal_layer_id=raw.get("terminal_layer_id", _TERMINAL_LAYER_ID),
        no_layer_after_p12=raw.get("no_layer_after_p12", False),
        canonical_order=tuple(canonical_order_raw),
        _layers_by_id=layers_by_id,
    )

    _validate(snapshot, path)
    return snapshot


# ── module-level convenience accessors ────────────────────────────────────────

def get_layer(layer_id: str) -> LayerEntry:
    """Get a single LayerEntry from the loaded snapshot."""
    return load_snapshot().get_layer(layer_id)


def canonical_order() -> list[str]:
    """Return canonical layer IDs in pipeline order (P0→P12)."""
    return list(load_snapshot().canonical_order)


def terminal_layer_id() -> str:
    """Return the ID of the terminal layer (P12_IFADAH_SPEECH_FORCE)."""
    return load_snapshot().terminal_layer_id


def assert_no_p13() -> None:
    """Assert that no P13 exists in the registry."""
    load_snapshot().assert_no_p13()
